import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Contabilizzara</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1> */}
        <Image src="/logo.png" alt="Logo" width={200} height={256} />

        <p className={styles.description}>
          Contabilidade para sua empresa
        </p>

        <div className={styles.grid}>
          <a  href="https://wa.me/5527997918153"  className={styles.card} >
            <h2>Fale conosco &rarr;</h2>
            <p>Fale agora com um consultor.</p>
          </a>

          <a href="" className={styles.card}>
            <h2>Quem somos &rarr;</h2>
            <p>Saiba mais sobre a Contabilizzara</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Clientes e parceiros &rarr;</h2>
            <p>Conheça nossos clientes e pareceiros</p>
          </a>

          <a
            href=""
            className={styles.card}
          >
            <h2>Blog &rarr;</h2>
            <p>
              Veja noticias em nosso blog, não fique de fora!
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a rel="noopener noreferrer" >
          <span className={styles.logo}>
          Powered by rdmobile
          </span>
        </a>
      </footer>
    </div>
  )
}
